// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpa2gPk5i_vIjxIPm6JssZk8-9zRu75o',
    appId: '1:692493273607:ios:e10456b6dc8aff657738a2',
    messagingSenderId: '692493273607',
    projectId: 'choremate-82c08',
    storageBucket: 'choremate-82c08.firebasestorage.app',
    iosClientId: '692493273607-qfravqeu1jo1gkhs5lqnt8kdnobfad85.apps.googleusercontent.com',
    iosBundleId: 'com.example.choremateApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoImda8dDzDyWbPT82i08VMrAjRKYwY1E',
    appId: '1:692493273607:web:4abfb7f90996720b7738a2',
    messagingSenderId: '692493273607',
    projectId: 'choremate-82c08',
    authDomain: 'choremate-82c08.firebaseapp.com',
    storageBucket: 'choremate-82c08.firebasestorage.app',
    measurementId: 'G-DQQBFZC4GV',
  );

}